# Generated by Django 6.0.7 on 2026-07-31 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('lecture', 'Lecture'), ('exam', 'Exam'), ('event', 'Event')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('recurrence_rule', models.CharField(blank=True, max_length=255, null=True)),
                ('recurrence_start_date', models.DateField(blank=True, null=True)),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('shifted', 'Shifted'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('academic_session', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_timetable_entries', to='accounts.adminofficer')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='LectureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('session_start_time', models.TimeField()),
                ('session_end_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('shifted', 'Shifted'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled'), ('held', 'Held'), ('not_held', 'Not Held')], default='scheduled', max_length=20)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_sessions', to='venues.venue')),
                ('timetable_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='scheduling.timetableentry')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_candidates_count', models.IntegerField()),
                ('invigilators', models.ManyToManyField(blank=True, related_name='invigilated_exams', to='accounts.lecturerstaff')),
                ('timetable_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sitting', to='scheduling.timetableentry')),
            ],
        ),
    ]
