# Generated by Django 6.0.7 on 2026-09-11 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_student_program"),
        ("hierarchy", "0004_create_default_programs"),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetableentry",
            name="academic_session",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.CreateModel(
            name="AcademicSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_sessions",
                        to="hierarchy.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("first", "First Semester"),
                            ("second", "Second Semester"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "duration_type",
                    models.CharField(
                        choices=[
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("fixed", "Fixed End Date"),
                        ],
                        default="fixed",
                        max_length=10,
                    ),
                ),
                (
                    "duration_value",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of weeks or months if applicable.",
                        null=True,
                    ),
                ),
                ("lecture_start_date", models.DateField(blank=True, null=True)),
                ("lecture_end_date", models.DateField(blank=True, null=True)),
                ("exam_start_date", models.DateField(blank=True, null=True)),
                ("exam_end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_semesters",
                        to="accounts.adminofficer",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semesters",
                        to="scheduling.academicsession",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "name"],
            },
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timetable_entries",
                to="scheduling.semester",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicsession",
            constraint=models.UniqueConstraint(
                fields=("school", "label"), name="unique_session_label_per_school"
            ),
        ),
        migrations.AddConstraint(
            model_name="academicsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("school",),
                name="unique_current_session_per_school",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("session", "name")},
        ),
    ]
