# Generated by Django 6.0.7 on 2026-09-14 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0004_create_default_programs'),
        ('scheduling', '0003_default_session_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationScopePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_faculty_generation', models.BooleanField(default=False)),
                ('allow_department_generation', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_permission', to='hierarchy.school')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableGenerationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('school', 'School'), ('faculty', 'Faculty'), ('department', 'Department')], max_length=20)),
                ('scope_id', models.PositiveIntegerField()),
                ('scope_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_status', models.CharField(choices=[('optimal', 'Optimal'), ('feasible', 'Feasible'), ('best_available', 'Best Available'), ('failed', 'Failed')], default='best_available', max_length=20)),
                ('hard_conflicts_count', models.PositiveIntegerField(default=0)),
                ('student_conflicts_count', models.PositiveIntegerField(default=0)),
                ('lecturer_conflicts_count', models.PositiveIntegerField(default=0)),
                ('venue_conflicts_count', models.PositiveIntegerField(default=0)),
                ('daily_limit_violations_count', models.PositiveIntegerField(default=0)),
                ('occurrence_day_violations_count', models.PositiveIntegerField(default=0)),
                ('capacity_penalty', models.PositiveIntegerField(default=0)),
                ('fitness_score', models.FloatField(default=0.0)),
                ('conflict_report', models.JSONField(blank=True, default=dict)),
                ('generation_metrics', models.JSONField(blank=True, default=dict)),
                ('assignments_payload', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_generation_runs', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_runs', to='scheduling.semester')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
