# Generated by Django 6.0.7 on 2026-10-03 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_adminofficer_level'),
        ('hierarchy', '0004_create_default_programs'),
        ('scheduling', '0004_generationscopepermission_timetablegenerationrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationscopepermission',
            name='allow_faculty_exam_period',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FacultyExamPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_faculty_exam_periods', to='accounts.adminofficer')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_periods', to='hierarchy.faculty')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_exam_periods', to='scheduling.semester')),
            ],
            options={
                'ordering': ['semester', 'faculty'],
                'unique_together': {('semester', 'faculty')},
            },
        ),
    ]
