# Generated by Django 6.0.7 on 2026-10-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_generationscopepermission_allow_faculty_exam_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='max_semesters',
            field=models.PositiveSmallIntegerField(default=2, help_text='Configured number of semesters for this session.'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('third', 'Third Semester'), ('fourth', 'Fourth Semester')], max_length=20),
        ),
    ]
