# Generated by Django 6.0.7 on 2026-10-05 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0004_create_default_programs'),
        ('scheduling', '0006_academicsession_max_semesters_alter_semester_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='target_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional target level for events (e.g. 100, 200, 300, 400, 500). Null means general / all levels.', null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='target_program',
            field=models.ForeignKey(blank=True, help_text='Optional target program cohort for department/faculty/school events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_timetable_entries', to='hierarchy.program'),
        ),
    ]
