# Generated by Django 6.0.7 on 2026-10-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_timetableentry_target_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('shifted', 'Shifted'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled'), ('pending_approval', 'Pending Approval')], default='scheduled', max_length=20),
        ),
    ]
