[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=26.5.1",
    "django>=6.0.7",
    "django-anymail>=15.0",
    "django-celery-beat>=2.9.0",
    "django-cors-headers>=4.9.0",
    "django-environ>=0.14.0",
    "django-filter>=26.1",
    "djangorestframework>=3.17.1",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.30.0",
    "factory-boy>=3.3.3",
    "firebase-admin>=7.5.0",
    "psycopg2-binary>=2.9.12",
    "pytest>=9.1.1",
    "pytest-django>=4.12.0",
    "ruff>=0.16.0",
]
