# Generated by Django 6.0.7 on 2026-07-31 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRepReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held', models.BooleanField()),
                ('reason', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('window_expires_at', models.DateTimeField()),
                ('lecturer_response', models.TextField(blank=True, null=True)),
                ('lecturer_responded_at', models.DateTimeField(blank=True, null=True)),
                ('lecture_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='scheduling.lecturesession')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='UnreportedSessionFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_flags', to='accounts.adminofficer')),
                ('lecture_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unreported_flag', to='scheduling.lecturesession')),
            ],
        ),
    ]
