# Generated by Django 6.0.7 on 2026-08-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminofficer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
