# Generated by Django 6.0.7 on 2026-09-11 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_adminofficer_email"),
        ("hierarchy", "0004_create_default_programs"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="hierarchy.program",
            ),
        ),
    ]
