# Generated by Django 6.0.7 on 2026-10-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_assign_students_to_default_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminofficer',
            name='level',
            field=models.CharField(choices=[('system', 'System'), ('university', 'University'), ('school', 'School'), ('faculty', 'Faculty'), ('department', 'Department')], max_length=20),
        ),
    ]
