# Generated by Django 6.0.7 on 2026-10-08 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_adminofficer_level'),
        ('hierarchy', '0004_create_default_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminofficer',
            name='is_exam_officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminofficer',
            name='is_lecturer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminofficer',
            name='lecturer_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_admins', to='hierarchy.department'),
        ),
    ]
