# Generated by Django 6.0.7 on 2026-08-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='max_level',
            field=models.PositiveIntegerField(default=400),
        ),
    ]
