# Generated by Django 6.0.7 on 2026-09-11 20:41

import django.db.models.deletion
import hierarchy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0002_department_max_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        max_length=20,
                        validators=[hierarchy.models.validate_code_format],
                    ),
                ),
                ("max_level", models.PositiveIntegerField(default=400)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="hierarchy.department",
                    ),
                ),
            ],
            options={
                "ordering": ["department__name", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("department", "code"),
                        name="unique_program_code_per_department",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("department",),
                        name="unique_default_program_per_department",
                    ),
                ],
            },
        ),
    ]
