# Generated by Django 6.0.7 on 2026-07-31 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discrepancies', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discrepancyrequest',
            name='request_type',
            field=models.CharField(choices=[('shift_venue', 'Shift Venue'), ('shift_time', 'Shift Time'), ('postpone', 'Postpone'), ('cancel', 'Cancel'), ('create_booking', 'Create Booking')], max_length=30),
        ),
        migrations.AlterField(
            model_name='discrepancyrequest',
            name='timetable_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discrepancy_requests', to='scheduling.timetableentry'),
        ),
    ]
