# Generated by Django 6.0.7 on 2026-08-01 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discrepancies', '0002_alter_discrepancyrequest_request_type_and_more'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discrepancyrequest',
            name='lecture_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discrepancy_requests', to='scheduling.lecturesession'),
        ),
        migrations.AddField(
            model_name='discrepancyrequest',
            name='proposed_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discrepancyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
    ]
