# Generated by Django 6.0.7 on 2026-09-08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("accounts", "0002_adminofficer_email"), ("hierarchy", "0002_department_max_level")]

    operations = [
        migrations.CreateModel(
            name="DepartmentStudentCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("count", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("level", models.PositiveIntegerField()),
                ("department", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="student_counts", to="hierarchy.department")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_student_counts", to="accounts.adminofficer")),
            ],
            options={"ordering": ("department__faculty__school__name", "department__faculty__name", "department__name", "level")},
        ),
        migrations.AddConstraint(
            model_name="departmentstudentcount",
            constraint=models.UniqueConstraint(fields=("department", "level"), name="unique_department_student_count_level"),
        ),
    ]
