# Generated by Django 6.0.7 on 2026-09-11 20:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_department_counts_to_program_counts(apps, schema_editor):
    DepartmentStudentCount = apps.get_model("student_counts", "DepartmentStudentCount")
    ProgramStudentCount = apps.get_model("student_counts", "ProgramStudentCount")
    Program = apps.get_model("hierarchy", "Program")

    for dsc in DepartmentStudentCount.objects.all():
        default_program = Program.objects.filter(department=dsc.department, is_default=True).first()
        if not default_program:
            default_program = Program.objects.filter(department=dsc.department).first()
        if default_program:
            ProgramStudentCount.objects.update_or_create(
                program=default_program,
                level=dsc.level,
                defaults={
                    "count": dsc.count,
                    "updated_by": dsc.updated_by,
                },
            )


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_student_program"),
        ("hierarchy", "0004_create_default_programs"),
        ("student_counts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramStudentCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField()),
                (
                    "count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_counts",
                        to="hierarchy.program",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_student_counts",
                        to="accounts.adminofficer",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "program__department__faculty__school__name",
                    "program__department__faculty__name",
                    "program__department__name",
                    "program__name",
                    "level",
                ),
            },
        ),
        migrations.AddConstraint(
            model_name="programstudentcount",
            constraint=models.UniqueConstraint(
                fields=("program", "level"), name="unique_program_student_count_level"
            ),
        ),
        migrations.RunPython(
            migrate_department_counts_to_program_counts,
            reverse_migration,
        ),
        migrations.DeleteModel(
            name="DepartmentStudentCount",
        ),
    ]
