# Generated by Django 6.0.7 on 2026-07-31 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('venue_type', models.CharField(choices=[('lecture_hall', 'Lecture Hall'), ('laboratory', 'Laboratory'), ('exam_hall', 'Exam Hall'), ('multipurpose', 'Multipurpose')], max_length=30)),
                ('capacity', models.IntegerField()),
                ('exam_capacity', models.IntegerField(blank=True, null=True)),
                ('owning_level', models.CharField(choices=[('department', 'Department'), ('faculty', 'Faculty'), ('school', 'School')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facilities', models.ManyToManyField(blank=True, related_name='venues', to='venues.facility')),
                ('owning_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_venues', to='hierarchy.department')),
                ('owning_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_venues', to='hierarchy.faculty')),
                ('owning_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_venues', to='hierarchy.school')),
            ],
        ),
    ]
