# Generated by Django 6.0.7 on 2026-07-31 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('owning_level', models.CharField(choices=[('department', 'Department'), ('faculty', 'Faculty'), ('school', 'School'), ('general', 'General')], max_length=20)),
                ('lecturers', models.ManyToManyField(blank=True, related_name='assigned_courses', to='accounts.lecturerstaff')),
                ('owning_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_courses', to='hierarchy.department')),
                ('owning_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_courses', to='hierarchy.faculty')),
                ('owning_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_courses', to='hierarchy.school')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_to_level', models.CharField(choices=[('department', 'Department'), ('faculty', 'Faculty'), ('school', 'School')], max_length=20)),
                ('direction', models.CharField(choices=[('offered', 'Offered'), ('requested', 'Requested')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='courses.course')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_course_grants', to='accounts.adminofficer')),
                ('granted_to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_access_grants', to='hierarchy.department')),
                ('granted_to_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_access_grants', to='hierarchy.faculty')),
                ('granted_to_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_access_grants', to='hierarchy.school')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_course_grants', to='accounts.adminofficer')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'academic_session')},
            },
        ),
    ]
