# Generated by Django 6.0.7 on 2026-09-11 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("hierarchy", "0004_create_default_programs"),
        ("scheduling", "0002_academic_session_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="program_scope",
            field=models.CharField(
                choices=[
                    ("general", "General (all programs)"),
                    ("program", "Program-Specific"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="scheduling.semester",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="target_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targeted_courses",
                to="hierarchy.program",
            ),
        ),
        migrations.AddField(
            model_name="courseaccessgrant",
            name="grant_scope",
            field=models.CharField(
                choices=[
                    ("general", "General (all programs)"),
                    ("program", "Program-Specific"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="courseaccessgrant",
            name="target_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_grants",
                to="hierarchy.program",
            ),
        ),
    ]
