# Generated by Django 6.0.7 on 2026-09-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_semester_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('practical', 'Practical')], default='lecture', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='required_occurrences_per_week',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
