# Generated by Django 6.0.7 on 2026-10-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_devicetoken_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('discrepancy_submitted', 'Discrepancy Submitted'), ('discrepancy_approved', 'Discrepancy Approved'), ('discrepancy_rejected', 'Discrepancy Rejected'), ('session_shifted', 'Session Shifted'), ('session_cancelled', 'Session Cancelled'), ('reporting_window_open', 'Reporting Window Open'), ('session_unreported', 'Session Unreported')], max_length=40),
        ),
    ]
